// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xfpga_top.h"

extern XFpga_top_Config XFpga_top_ConfigTable[];

XFpga_top_Config *XFpga_top_LookupConfig(u16 DeviceId) {
	XFpga_top_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XFPGA_TOP_NUM_INSTANCES; Index++) {
		if (XFpga_top_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XFpga_top_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XFpga_top_Initialize(XFpga_top *InstancePtr, u16 DeviceId) {
	XFpga_top_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XFpga_top_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XFpga_top_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

