%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/davidgs/Dropbox/ETH/Masterarbeit/report/figures_raw/topo-comparison/networks.xlsx
%    Worksheet: Tabelle1
%
% To extend the code for use with different selected data or a different
% spreadsheet, generate a function instead of a script.

% Auto-generated by MATLAB on 2016/07/23 14:17:57

%% Import the data
[~, ~, raw] = xlsread('/Users/davidgs/Dropbox/ETH/Masterarbeit/report/figures_raw/topo-comparison/networks.xlsx','Tabelle1');
raw = raw(3:end,:);
raw(cellfun(@(x) ~isempty(x) && isnumeric(x) && isnan(x),raw)) = {''};
cellVectors = raw(:,[1,7]);
raw = raw(:,[2,3,4,5,6]);

%% Create output variable
data = reshape([raw{:}],size(raw));

%% Allocate imported array to column variable names
name = cellVectors(:,1);
layers = data(:,1);
maccs = data(:,2);
params = data(:,3);
activations = data(:,4);
error_top5 = data(:,5);
source = cellVectors(:,2);

%% Clear temporary variables
clearvars data raw cellVectors;

save all_data.mat