
///////
// Network + Layer Configuration.
// File automatically generated by convert_caffemodel.py
// from deploy.prototxt and snapshot_iter_240240.caffemodel
// (c) 2016 David Gschwend
///////

#include "network.hpp"
network_t *get_network_config() {
  network_t *net = new network_t(27, 2528800);

  // Layer Attributes: ( NAME   ,   W,   H,   CI,  CO, K, P, S, R, S1, S2, GP)
  addLayer(net, layer_t("c1    ", 256, 256,    3,  64, 3, 1, 2, 1,  0,  0,  0));
  addLayer(net, layer_t("f2/s3 ", 128, 128,   64,  16, 3, 1, 2, 1,  0,  0,  0));
  addLayer(net, layer_t("f2/e1 ",  64,  64,   16,  64, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f2/e3 ",  64,  64,   16,  64, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("f3/s1 ",  64,  64,  128,  16, 1, 0, 1, 1,  0,  0,  0));
  addLayer(net, layer_t("f3/e1 ",  64,  64,   16,  64, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f3/e3 ",  64,  64,   16,  64, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("f4/s3 ",  64,  64,  128,  32, 3, 1, 2, 1,  0,  0,  0));
  addLayer(net, layer_t("f4/e1 ",  32,  32,   32, 128, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f4/e3 ",  32,  32,   32, 128, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("f5/s1 ",  32,  32,  256,  32, 1, 0, 1, 1,  0,  0,  0));
  addLayer(net, layer_t("f5/e1 ",  32,  32,   32, 128, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f5/e3 ",  32,  32,   32, 128, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("f6/s3 ",  32,  32,  256,  64, 3, 1, 2, 1,  0,  0,  0));
  addLayer(net, layer_t("f6/e1 ",  16,  16,   64, 256, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f6/e3 ",  16,  16,   64, 256, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("f7/s1 ",  16,  16,  512,  64, 1, 0, 1, 1,  0,  0,  0));
  addLayer(net, layer_t("f7/e1 ",  16,  16,   64, 192, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f7/e3 ",  16,  16,   64, 192, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("f8/s3 ",  16,  16,  384, 112, 3, 1, 2, 1,  0,  0,  0));
  addLayer(net, layer_t("f8/e1 ",   8,   8,  112, 256, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f8/e3 ",   8,   8,  112, 256, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("f9/s1 ",   8,   8,  512, 112, 1, 0, 1, 1,  0,  0,  0));
  addLayer(net, layer_t("f9/e1 ",   8,   8,  112, 368, 1, 0, 1, 1,  1,  0,  0));
  addLayer(net, layer_t("f9/e3 ",   8,   8,  112, 368, 3, 1, 1, 1,  0,  1,  0));
  addLayer(net, layer_t("c10/p1",   8,   8,  736, 512, 1, 0, 1, 0,  1,  0,  1));
  addLayer(net, layer_t("c10/p2",   8,   8,  736, 512, 1, 0, 1, 0,  0,  1,  1));

  net->num_weights = 2528800;
  const char* filename = "weights.bin";
  loadWeightsFromFile(net, filename);
  return net;
}
